-- =====================================================================
-- Esquema de base de datos para Microverse (Supabase)
-- Ejecuta este script en el editor SQL de tu panel de Supabase.
-- =====================================================================

-- 1. Crear la tabla de Categorías
CREATE TABLE IF NOT EXISTS public.categorias (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre character varying NOT NULL,
    fecha_creacion timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar Seguridad a Nivel de Fila (RLS) en categorias
ALTER TABLE public.categorias ENABLE ROW LEVEL SECURITY;

-- Crear política para permitir que cualquiera pueda leer las categorías
CREATE POLICY "Permitir lectura pública de categorías" ON public.categorias
    FOR SELECT USING (true);

-- 2. Crear la tabla de Modelos 3D
CREATE TABLE IF NOT EXISTS public.modelos_3d (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre character varying NOT NULL,
    archivo_modelo_url text NOT NULL,
    preview_url text,
    formato character varying,
    tamano_bytes bigint,
    fecha_creacion timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    descripcion text,
    categoria_id bigint REFERENCES public.categorias(id) ON DELETE SET NULL,
    
    -- Columnas opcionales para control estético y metadatos adicionales desde el backend.
    -- Si no existen o son NULL, la aplicación usará valores procedimentales automáticos.
    subtitle text,
    scientific_name text,
    primary_color character varying(7),   -- Formato HEX (ej: '#00A0FF')
    secondary_color character varying(7), -- Formato HEX (ej: '#C03DFF')
    visual_seed integer,
    is_elongated boolean DEFAULT false
);

-- Habilitar Seguridad a Nivel de Fila (RLS) en modelos_3d
ALTER TABLE public.modelos_3d ENABLE ROW LEVEL SECURITY;

-- Crear política para permitir que cualquiera pueda leer los modelos 3D
CREATE POLICY "Permitir lectura pública de modelos_3d" ON public.modelos_3d
    FOR SELECT USING (true);

-- =====================================================================
-- DATOS DE PRUEBA (Opcional: Descomenta las líneas de abajo para rellenar)
-- =====================================================================

/*
-- Insertar Categorías de ejemplo
INSERT INTO public.categorias (id, nombre) VALUES
(1, 'Tipos de células'),
(2, 'Microorganismos'),
(3, 'Protozoos'),
(4, 'Bacterias'),
(5, 'Virus')
ON CONFLICT (id) DO NOTHING;

-- Insertar Modelos 3D de ejemplo
INSERT INTO public.modelos_3d (id, nombre, archivo_modelo_url, preview_url, formato, tamano_bytes, descripcion, categoria_id, subtitle, scientific_name, primary_color, secondary_color, visual_seed, is_elongated) VALUES
(1, 'Célula animal', 'https://example.com/animal_cell.glb', NULL, 'glb', 1048576, 'Las células animales son unidades básicas de vida con núcleo y organelos rodeados por membrana.', 1, 'Célula eucariota', 'Cellula animalis', '#00A0FF', '#C03DFF', 14, false),
(2, 'Célula vegetal', 'https://example.com/plant_cell.glb', NULL, 'glb', 1572864, 'La célula vegetal posee pared celular, cloroplastos y una vacuola central que ayuda a mantener su estructura.', 1, 'Célula eucariota', 'Cellula plantae', '#3DD13D', '#158CDB', 22, false),
(3, 'Levadura', 'https://example.com/yeast.glb', NULL, 'glb', 524288, 'La levadura es un hongo unicelular usado para estudiar procesos celulares y fermentación.', 2, 'Hongo', 'Saccharomyces cerevisiae', '#708FFF', '#FF6140', 31, false),
(4, 'Paramecio', 'https://example.com/paramecium.glb', NULL, 'glb', 786432, 'El paramecio se desplaza mediante cilios y vive en ambientes acuáticos.', 3, 'Protozoo', 'Paramecium caudatum', '#15DB94', '#EBC729', 44, true),
(5, 'Ameba', 'https://example.com/amoeba.glb', NULL, 'glb', 1153433, 'La ameba cambia de forma para desplazarse y capturar alimento mediante seudópodos.', 3, 'Protozoo', 'Amoeba proteus', '#87BDFF', '#FF7324', 51, false),
(6, 'Euglena', 'https://example.com/euglena.glb', NULL, 'glb', 943718, 'La euglena combina rasgos vegetales y animales, y puede moverse con un flagelo.', 3, 'Protozoo', 'Euglena gracilis', '#7AE814', '#00C79E', 63, true),
(7, 'Escherichia coli', 'https://example.com/ecoli.glb', NULL, 'glb', 419430, 'E. coli es una bacteria frecuente en estudios de genética, salud y microbiología.', 4, 'Bacteria', 'Escherichia coli', '#BAF240', '#2BC245', 72, true),
(8, 'Adenovirus', 'https://example.com/adenovirus.glb', NULL, 'glb', 2097152, 'Los adenovirus son virus de ADN que pueden causar infecciones respiratorias y oculares.', 5, 'Virus', 'Adenoviridae', '#8C45FF', '#12A1FF', 83, false),
(9, 'Virus influenza', 'https://example.com/influenza.glb', NULL, 'glb', 1887436, 'El virus influenza contiene ARN y posee proteínas de superficie relevantes para su identificación.', 5, 'Virus', 'Orthomyxoviridae', '#00C5FF', '#FF3BDB', 95, false)
ON CONFLICT (id) DO NOTHING;

-- Ajustar secuencias de ID
SELECT setval('categorias_id_seq', COALESCE((SELECT MAX(id)+1 FROM categorias), 1), false);
SELECT setval('modelos_3d_id_seq', COALESCE((SELECT MAX(id)+1 FROM modelos_3d), 1), false);
*/
