-- =====================================================================
-- Esquema de base de datos para Microverse (Supabase)
-- =====================================================================

-- 1. Crear la tabla de Categorías
CREATE TABLE IF NOT EXISTS public.categorias (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre character varying NOT NULL,
    fecha_creacion timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar Seguridad a Nivel de Fila (RLS) en categorias
ALTER TABLE public.categorias ENABLE ROW LEVEL SECURITY;

-- Crear política para permitir que cualquiera pueda leer las categorías
CREATE POLICY "Permitir lectura pública de categorías" ON public.categorias
    FOR SELECT USING (true);

-- 2. Crear la tabla de Modelos 3D
CREATE TABLE IF NOT EXISTS public.modelos_3d (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre character varying NOT NULL,
    archivo_modelo_url text NOT NULL,
    preview_url text,
    formato character varying,
    tamano_bytes bigint,
    fecha_creacion timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    descripcion text,
    categoria_id bigint REFERENCES public.categorias(id) ON DELETE SET NULL,
    
    -- Columnas opcionales para control estético y metadatos adicionales desde el backend.
    -- Si no existen o son NULL, la aplicación usará valores procedimentales automáticos.
    subtitle text,
    scientific_name text,
    primary_color character varying(7),   -- Formato HEX (ej: '#00A0FF')
    secondary_color character varying(7), -- Formato HEX (ej: '#C03DFF')
    visual_seed integer,
    is_elongated boolean DEFAULT false
);

-- Habilitar Seguridad a Nivel de Fila (RLS) en modelos_3d
ALTER TABLE public.modelos_3d ENABLE ROW LEVEL SECURITY;

-- Crear política para permitir que cualquiera pueda leer los modelos 3D
CREATE POLICY "Permitir lectura pública de modelos_3d" ON public.modelos_3d
    FOR SELECT USING (true);
